apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: vkpaints-dev-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: user-service
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: user-container
        image: ghcr.io/vk-paints/vkpaints-user-service:v1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: user-config
        # - secretRef:
        #     name: user-service-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10

        ports:
        - containerPort: 3000

