name: CI Prod Pipeline
on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  validate:
    if: github.event_name == 'push'
    uses: VK-Paints/vkpaints-workflow/.github/workflows/reusable-ci-prod.yml@main
    with:
      service_name: user-service
      smtp_server: ${{ vars.SMTP_SERVER }}
      smtp_port: ${{ vars.SMTP_PORT }}
      mail_from: ${{ vars.MAIL_FROM }}
      publish: false
    secrets: inherit

  release:
    if: github.event_name == 'release'
    uses: VK-Paints/vkpaints-workflow/.github/workflows/reusable-ci-prod.yml@main
    with:
      service_name: user-service
      smtp_server: ${{ vars.SMTP_SERVER }}
      smtp_port: ${{ vars.SMTP_PORT }}
      mail_from: ${{ vars.MAIL_FROM }}
      publish: true
      image_tag: ${{ github.event.release.tag_name }}
    secrets: inherit
