name: 🚀 CI Prod Pipeline
on:
  push:
    branches: [ main ]
jobs:
  prod:
    uses: VK-Paints/vkpaints-workflow/.github/workflows/unified-pipeline.yml@main
    with:
      service_name: user-service
      smtp_server: ${{ vars.SMTP_SERVER }}
      smtp_port: ${{ vars.SMTP_PORT }}
      mail_from: ${{ vars.MAIL_FROM }}
    secrets: inherit
