name: Dev Build & Push
on:
  push:
    branches: [ main ]
jobs:
  build:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: VK-Paints/vkpaints-workflow/.github/workflows/build-push-dev.yml@main
    with:

      smtp_server: ${{ vars.SMTP_SERVER }}
      smtp_port: ${{ vars.SMTP_PORT }}
      mail_from: ${{ vars.MAIL_FROM }}

    secrets: inherit

