name: PR Security Scans
on:
  pull_request:
    branches: [ main ]
jobs:
  scans:
    uses: VK-Paints/vkpaints-workflow/.github/workflows/pr-scans.yml@main
    with:
      service_name: user-service
    secrets: inherit
