name: PR Security Scans
on:
  pull_request:
    branches: [ main ]
jobs:
  scans:
    uses: VK-Paints/vkpaints-workflow/.github/workflows/pr-scans.yml@main
    with:

      smtp_server: ${{ vars.SMTP_SERVER }}
      smtp_port: ${{ vars.SMTP_PORT }}
      mail_from: ${{ vars.MAIL_FROM }}

    secrets: inherit

