name: Production Release
on:
  release:
    types: [ published ]
jobs:
  release:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: VK-Paints/vkpaints-workflow/.github/workflows/build-push-release.yml@main
    with:
      service_name: user-service
    secrets: inherit
