name: Production Release
on:
  release:
    types: [ published ]
jobs:
  release:
    uses: VK-Paints/vkpaints-workflow/.github/workflows/build-push-release.yml@main
    with:
      service_name: user-service
    secrets: inherit
